-- https://programmers.co.kr/learn/courses/30/lessons/59042

SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_OUTS AS OUTS
LEFT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID is null
ORDER BY ANIMAL_ID